### ISSUE TITLE
multi seed generate on template

### ISSUE THREAD

**Issue by be99inner** [opsta/ansible-cassandra#3]
- some generate seed is a problem with multi seeds

**Comment by be99inner** [comment]
on install tasks of playbook need to run gather_facts of all hosts.
```yml
---
- hosts: all
  gather_facts: true
```
